### ISSUE TITLE
DMP mode

### ISSUE THREAD

**Issue by tarasii** [Golly-Rui/STM32_DMP_Driver#1]
https://github.com/Guoli-Lyu/STM32_DMP_Driver/blob/1cb9fc60aa27d305af3ae3e8830d6e71f74e29bd/Source/MPU6050/mpu6050.c#L107

Hi!

I found your mpu driver for stm32. And missing some DMP staff.
Do you use DMP mode, with fifo buffer? I see in MPU6050_newValues you make sum "by hands". 
Look like in DMP mode MPU make this by DSP filter. That filter have to be more accurate and quicker than sum is.

Buy!

**Comment by fMeow** [comment]
That's interesting, how can I use DSP filter for this task?

**Comment by tarasii** [comment]
Hi,

DMP mode can do smoothing filter for sensor results. Even got android
movement filter. It operates quicker, and do not use memory and processor
time from main processor.

This chip got DSP, firstly have to load filter firmware to DSP, than adjust
sensors, buffer and turn dsp mode on. I got this code ported for stm, but
it doesn't work.

Actually I see working code for arduino and it very different from
manufactor firmvare for msp430

чт, 22 авг. 2019 г., 6:07 Guoli Lyu <notifications@github.com>:

**Comment by fMeow** [comment]
Well, I actually have ported two version of MPU6050 DMP driver. One from TI  for msp430 **in the master branch**, while another from arduino I2Cdev **in the I2Cdev branch**. Have you tried the later one?

I have got both version of DMP driver working on my STM32F103C8T6. I noticed that the one from arduino requires much more resources than the other.

**Comment by tarasii** [comment]
Thanks, I'll try it. May be I missed something half a year ago.
