### ISSUE TITLE
6 axis data to position

### ISSUE THREAD

**Issue by goog** [Golly-Rui/STM32_DMP_Driver#3]
你好，有了六轴数据怎么计算惯导位置

**Comment by fMeow** [comment]
可以用硬件DMP或者手动加卡尔曼滤波之类的来做姿态融合

**Comment by goog** [comment]
姿态融合 不太懂，有没有什么参考资料呢

**Comment by fMeow** [comment]
如果目标单片机FLASH空间还可以的话，建议用MPU的硬件DMP得到四元数，然后自己换算成yaw-roll-pitch，这样单片机的运算压力小很多。

我移植的两个库里面都有DMP相关的代码，master分支上的占用资源比较少，I2Cdev分支的整体代码比较完善，可以参考一下。

想自己算的话会比较麻烦。可以先看看[crazypony的文档](http://www.crazepony.com/book/about-algorithm.html)初步了解一下。

**Comment by goog** [comment]
好的 谢了
